<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('mfCategory', 'doctrine');

/**
 * BasemfCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Phrases
 * 
 * @method string              getName()    Returns the current record's "name" value
 * @method Doctrine_Collection getPhrases() Returns the current record's "Phrases" collection
 * @method mfCategory          setName()    Sets the current record's "name" value
 * @method mfCategory          setPhrases() Sets the current record's "Phrases" collection
 * 
 * @package    frases
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemfCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mf_category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_spanish_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('mfPhrase as Phrases', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}