<?php

/**
 * mfCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mfCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mfCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mfCategory');
    }
}