<?php

/**
 * mfCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mfCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mfCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mfComment');
    }
}