<?php

/**
 * mfPhrasesFavorityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mfPhrasesFavorityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mfPhrasesFavorityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mfPhrasesFavority');
    }
    
    public function getFrasesFavoritas($user_id){
      $q = $this->createQuery('f');
      $q->innerJoin('f.mfPhrase p');
      $q->where('f.user_id = ?',$user_id);
      $result = $q->execute();
    
      return $result;
    }
}