<?php

/**
 * mfPhraseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mfPhraseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mfPhraseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mfPhrase');
    }
}