<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable {

  /**
   * Returns an instance of this class.
   *
   * @return object sfGuardUserTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('sfGuardUser');
  }

  public function getUsersActive($limit) {
    $q = $this->createQuery();
    $q->select('id, gender, username, uniq');
    $q->where('is_active =?', true);
    $q->orderBy('last_login DESC');
    $q->limit($limit);
    $result = $q->fetchArray();
    
    return $result;
  }

}