<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/07/26 01:51:21

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=frases',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
