<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/07/26 01:51:21
sfConfig::add(array(
  'app_s_css' => 'http://www.mis-frases.local/css/',
  'app_s_js' => 'http://www.mis-frases.local/js/',
  'app_s_img' => 'http://www.mis-frases.local/images/',
  'app_time_out' => 1800,
  'app_cookie_domain' => 'mis-frases.local',
));
