<?php

/**
 * BasesfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $gender
 * @property sfGuardUser $User
 * 
 * @method integer            getUserId()  Returns the current record's "user_id" value
 * @method string             getGender()  Returns the current record's "gender" value
 * @method sfGuardUser        getUser()    Returns the current record's "User" value
 * @method sfGuardUserProfile setUserId()  Sets the current record's "user_id" value
 * @method sfGuardUserProfile setGender()  Sets the current record's "gender" value
 * @method sfGuardUserProfile setUser()    Sets the current record's "User" value
 * 
 * @package    frases
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_profile');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('gender', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}