# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:
#all:
#  recaptcha:
#    active:     true
#    publickey:  "6LcXQMcSAAAAAAXbu94zeIISl4YrTM9hOCixnbU2"
#    privatekey: "6LcXQMcSAAAAAPVM0kLQTNvPfaM8G7yBqFhT3CTh"
#  mailhide:
#    publickey:  "6LcXQMcSAAAAAAXbu94zeIISl4YrTM9hOCixnbU2"
#    privatekey: "6LcXQMcSAAAAAPVM0kLQTNvPfaM8G7yBqFhT3CTh"