all:
  s_css: http://www.mis-frases.local/css/
  s_js:  http://www.mis-frases.local/js/
  s_img: http://www.mis-frases.local/images/
  
  time_out:  1800
  cookie_domain: mis-frases.local
  recaptcha:
    active:     true
    publickey:  "6LcXQMcSAAAAAAXbu94zeIISl4YrTM9hOCixnbU2"
    privatekey: "6LcXQMcSAAAAAPVM0kLQTNvPfaM8G7yBqFhT3CTh"
  mailhide:
    publickey:  "6LcXQMcSAAAAAAXbu94zeIISl4YrTM9hOCixnbU2"
    privatekey: "6LcXQMcSAAAAAPVM0kLQTNvPfaM8G7yBqFhT3CTh"