all:
#  stylesheets:    [modulos.css]
userSendFriendSuccess:
  stylesheets: [estilo-form.css]
userReadCommentSuccess:
  stylesheets: [estilo-form.css]
indexSuccess:
  stylesheets: [starrating.css]
  javascripts: [jquery.min.js,  starrating.js]