generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:   Lista de Usuarios
        display: [=username, email_address, first_name, last_name, is_active, is_super_admin, created_at]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
