connection: doctrine
detect_relations: true
options:
  type: INNODB
  collate: utf8_spanish_ci
  charset: utf8
###################################  

mfCategory:
  tableName: mf_category
  actAs:
    Timestampable: ~ 
    Sluggable:
      fields: [name]
  columns:
    name: { type: string(255), notnull: true, unique: true }

mfPhrase:
  tableName: mf_phrase
  actAs: { Timestampable: ~ }
  columns:
    title:
      type: string(50000)
    content:
      type: string(50000)
      notnull: true
    category_id:
      type: integer
      notnull: true
    author:
      type: string(50000)
    user_id:
      type: integer
      notnull: true
    visits:
      type: integer
      notnull: true
      default: 0
    comments:
      type: integer
      notnull: true
      default: 0
    counter_rate:
      type: integer
      default: 0
    value_rate:
      type: integer
      default: 0
  relations:
    Category:
      class: mfCategory
      foreignAlias: Phrases
      local: category_id
      foreign: id
    User:
      class: sfGuardUser
      foreignAlias: Phrases
      local: user_id
      foreign: id
      
      
mfComment:
  tableName: mf_comment
  actAs: { Timestampable: ~ }
  columns:
    comment:
      type: string(5000)
      notnull: true
    user_id:
      type: integer
      notnull: true
    phrase_id:
      type: integer
      notnull: true
  relations:
    sfGuardUser: { onDelete: CASCADE, local: user_id, foreign: id, foreignAlias: MfComments } 
    mfPhrase: { onDelete: CASCADE, local: phrase_id, foreign: id, foreignAlias: MfComments } 
    
    
    
mfPhrasesFavority:
  tableName: mf_phrases_favority
  actAs: { Timestampable: ~ }
  columns:
    user_id:
      type: integer
      notnull: true
    phrase_id:
      type: integer
      notnull: true
  relations:
    sfGuardUser: { onDelete: CASCADE, local: user_id, foreign: id, foreignAlias: Favorities } 
    mfPhrase: { onDelete: CASCADE, local: phrase_id, foreign: id, foreignAlias: Favorities } 